dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
    secure: L9SCAq7bUhHvk+0klkKd0F7QV/+gHBKXi7DB3cyLU5E1lgbfntMwZvsY8+mMeImNj50/j+pN53m/z7pFNlIAyEdVY1vJWp6vaoFA+wvvFPyBGLqJ/LPR0B0pbgIr0lDYR1rTSLaoa4LbEc3/eLJWknV0alPF6UQ1xEI146vKlV6kT7ow9iWQlhbmJKFo1VQMV56dCN97D4igJYhjmqjCXkzbI1oKijndVXZYzuGZ7bJmlk1cYE+Tpqp0KG3lSSuiwD5T4/abU3vN7NE+U+Kdp5hQYEBl81ZLoJ4LRba5CnK8cFXEP30ngaimUfL5HH81FK2uf9N0UJ5kdutYtKHF3hzaoycIp+ZERS2klgmlykKkgnMrLSqLymQRCrL4/7g4bhg59iuPqYJmMAboyOwYCOCqtyOdHb9/OaLwgRNZ7p7XoSoDYyG9Gn1tgwFTl4lXifYDb89d5+V/flJCAewO29K9bwM7pUpfd+atykevQMngcplMIIRJtvuaCX06IncBMyrrVxaJx23tjf+AT4wf2JSb7W/IFUywBPMpempV4IusTodMgmcOI0CVaLMFt2uMwq8WuVUguK5aA5xs9yHLTZIsgGA0QhZcycqLeq1j0sr3dvJARKGYE5eUcZmJLYfId/9+iqp01QLboWdWbyw0QRYoIs15YftpnJ8sHSrKEz0=
